import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import React, { useEffect, useState } from 'react';
import { SessionProvider } from 'next-auth/react';
import SessionProviderWrapper from './components/SessionProviderWrapper';
import { Noto_Sans_JP } from "next/font/google";


const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"], // 必要なら"latin-ext"も指定可能
});

// const inter = Inter({ subsets: ['latin'] });
// const inter = Inter({ subsets: ['latin', 'japanese'] });


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export const metadata = {
  export const metadata: Metadata = {
  title: "アイミット株式会社 - 名古屋市で安心と実績",
  description: "名古屋市での住宅設備のプロフェッショナルサービスを提供するアイミット株式会社の公式サイト。",
  robots: "noindex, follow",
  authors: [{ name: "アイミット株式会社" }],
};


export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode;
}) {

  const bodyClassName = notoSansJP.className
  ? notoSansJP.className.replace('vsc-initialized', '').trim()
  : "";
// console.log("Server ClassName:", bodyClassName);


  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "会社名",
              "url": "https://aimit.jp",
              "description": "会社全体に関する説明を記載。",
            }),
          }}
        />
      </head>
      <body className={`${bodyClassName} min-h-screen flex flex-col`}>
          {/* <SessionProviderWrapper>
            <Navbar />
              {children}
            <Footer />
          </SessionProviderWrapper> */}
           <SessionProviderWrapper>
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
            
          </SessionProviderWrapper>
          <Footer />

        </body>
    </html>
  );
}